### ISSUE TITLE
Backlinking within tabs (codeblocks)

### ISSUE THREAD

**Issue by hornjbl** [ptournet/obsidian-html-tabs#2]
Hi there... really enjoy the plugin, except for one little snag. It seems that backlinks are not enabled within code blocks. I can create the link, and click on it, but it doesn't show up in the backlink or outgoing link sections, which is what I need it to do like normal links would.

**Comment by ptournet** [comment]
> Hi there... really enjoy the plugin, except for one little snag. It seems that backlinks are not enabled within code blocks. I can create the link, and click on it, but it doesn't show up in the backlink or outgoing link sections, which is what I need it to do like normal links would.

Thanks for your comment! I will go and check that out... I'm not surprised though, as it's tricky to get the inside of a codeblock interacting with the Obsidian framework...

**Comment by ptournet** [comment]
This should works in version 1.1.0 that was just released. Let me know if you still encounter problems.
